#!/usr/bin/env bash
# This script makes up a story using the content of /etc/passwd

while IFS=: read -r username password _ gid _ home shell; do
  echo "The user $username is part of the $gid gang, lives in $home and rides $shell. USER ID's place is protected by the passcode $password, more info about the user here: $username"
done < /etc/passwd
